---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(p8105.datasets)
data("instacart")
library(plotly)
library(viridis)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot

```{r,echo=FALSE}
instacart |> 
  count(aisle) |> 
  arrange(desc(n)) |> 
  mutate(aisle = fct_reorder(aisle, n, .desc = TRUE)) |> 
   plot_ly(x = ~aisle, y = ~n, type = "scatter", colors = "viridis") |>
  layout(title = "Number of Items per Aisle", xaxis = list(title = "Aisles"), 
         yaxis = list(title = "Items"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Barchart

```{r,echo=FALSE}
instacart |> 
  count(aisle) |> 
  arrange(desc(n)) |> 
  mutate(aisle = fct_reorder(aisle, n, .desc = TRUE)) |> 
   plot_ly(x = ~aisle, y = ~n, type = "bar", colors = "viridis") |>
  layout(title = "Number of Items per Aisle", xaxis = list(title = "Aisles"), 
         yaxis = list(title = "Items"))
```

### Line plot

```{r,echo=FALSE}
instacart |> 
  count(aisle) |> 
  arrange(desc(n)) |> 
  mutate(aisle = fct_reorder(aisle, n, .desc = TRUE)) |> 
   plot_ly(x = ~aisle, y = ~n, type = "scatter", mode = "lines", colors = "viridis") |>
  layout(title = "Number of Items per Aisle", xaxis = list(title = "Aisles"), 
         yaxis = list(title = "Items"))
```

