---
title: "plotly"
output: html_document
date: '2023-11-02'
---

```{r}
library(tidyverse)
library(dplyr)
library(p8105.datasets)
data("instacart")
library(plotly)
```

```{r}
instacart = 
  instacart |> 
  as_tibble()
  
instacart |> 
  count(aisle) |> 
  arrange(desc(n))  

instacart |> 
  count(aisle) |> 
  filter(n > 10000) |> 
  mutate(aisle = fct_reorder(aisle, n)) 
```

## My scatterplot

```{r}
instacart |> 
  count(aisle) |> 
  arrange(desc(n)) |> 
  mutate(aisle = fct_reorder(aisle, n, .desc = TRUE)) |> 
   plot_ly(x = ~aisle, y = ~n, type = "scatter", colors = "viridis") |>
  layout(title = "Number of Items per Aisle", xaxis = list(title = "Aisles"), 
         yaxis = list(title = "Items"))

```

## My barchart

```{r}
instacart |> 
  count(aisle) |> 
  arrange(desc(n)) |> 
  mutate(aisle = fct_reorder(aisle, n, .desc = TRUE)) |> 
   plot_ly(x = ~aisle, y = ~n, type = "bar", colors = "viridis") |>
  layout(title = "Number of Items per Aisle", xaxis = list(title = "Aisles"), 
         yaxis = list(title = "Items"))
```

## My boxplot

```{r}
instacart |> 
  count(aisle) |> 
  arrange(desc(n)) |> 
  mutate(aisle = fct_reorder(aisle, n, .desc = TRUE)) |> 
   plot_ly(x = ~aisle, y = ~n, type = "box", colors = "viridis") |>
  layout(title = "Number of Items per Aisle", xaxis = list(title = "Aisles"), 
         yaxis = list(title = "Items"))
```

